version: "3.8"

networks:
  hydrion:
    driver: overlay

services:
  mongodb:
    image: mongo:latest
    networks:
      - hydrion
    environment:
      MONGO_INITDB_ROOT_USERNAME: hyriode
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/mongodb:/data/db

  redis:
    image: redis:6.2.6-alpine
    networks:
      - hydrion
    command: redis-server --requirepass p@ssw0rd

  hydrion:
    image: hydrion:latest
    ports:
      - "8080:8080"
    networks:
      - hydrion
    environment:
      MEMORY: 2G
    volumes:
      - ./data/hydrion:/usr/app/data